global:
  resolve_timeout: 5m

route:
  receiver: "all"      # 所有告警统一进入

receivers:
  - name: "all"
    webhook_configs:
      - url: "http://172.17.0.1:8081/alert/wechat"
        send_resolved: true
      - url: "http://172.17.0.1:5001/dingtalk"
        send_resolved: true
      - url: "http://172.17.0.1:8082/alert/sms"
        send_resolved: true
