server:
  port: 8006

spring:
  application:
    name: demo-server  # 服务名称
  # 服务名称+开发环境+文件后缀名 = nacos配置的Data Id     gateway-dev.yaml
  profiles:
    active: mac   #开发环境
  main:
    web-application-type: servlet
    allow-bean-definition-overriding: true
  config:
    import:
      - optional:nacos:datasource.yml
      - optional:nacos:minio.yml
      - optional:nacos:springdoc.yml
      - optional:nacos:redis.yml

  mail:
    host: smtp.qq.com
    username: # 请替换为你的QQ邮箱
    password:     # 请替换为你的QQ邮箱授权码
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

  # Hibernate DDL Configuration
  jpa:
    hibernate:
      ddl-auto: update  # Automatically updates the schema based on entity definitions
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect  # Use the correct dialect for your database
    database-platform: org.hibernate.dialect.MySQL8Dialect  # Optional, specify the database platform if needed
    show-sql: true  # Show SQL queries in the console for debugging
logging:
  level:
    com.alibaba.csp.sentinel: DEBUG  # Sentinel 的日志级别
    org.springframework.cloud: DEBUG  # Spring Cloud 相关的日志
    com.example: DEBUG  # 你自己应用的日志级别

wechat:
  pay:
    mock: true # Set to false to enable real payment
    appid: wx8888888888888888
    mchid: "1230000109"
    merchant-serial-number: "YOUR_MERCHANT_SERIAL_NUMBER"
    private-key-path: "classpath:apiclient_key.pem"
    api-v3-key: "YOUR_API_V3_KEY"
    notify-url: "https://yourdomain.com/api/wx-pay/notify"



---
spring:
  config:
    activate:
      on-profile: mac
  cloud:
    nacos:
      discovery:
        server-addr: @nacos.server-addr@
        group: spring-cloud-example-dev  # 需要在nacos 的namespace中创建，名字为spring-cloud-example-dev的Service
        namespace: cb500d3d-c86c-4230-8f7f-f5434caf711a   # 将spring-cloud-example-dev的namespace中id填入
        username: nacos
        password: nacos
      config:
        server-addr: @nacos.server-addr@
        group: spring-cloud-example-dev  # 需要在nacos 的namespace中创建，名字为spring-cloud-example-dev的Service
        namespace: cb500d3d-c86c-4230-8f7f-f5434caf711a   # 将spring-cloud-example-dev的namespace中id填入
        username: nacos
        password: nacos
        import-check:
          enabled: false
